# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: woopil-classting
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name


# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "3"

package:
  include:
    - node_modules/**

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2

plugins:
  - serverless-auto-swagger
  - serverless-plugin-typescript
  - serverless-offline


custom:
  autoswagger:
    title: '클래스팅 API 테스트'
    basePath: '/dev'
    apiKeyHeaders: ['Authorization']
    schemes: ["http"]
    typefiles: ['./src/dto/signupDto.ts', './src/dto/loginDto.ts', './src/dto/postSchoolDto.ts']


functions:
  signup:
    handler: src/user/signup.handler
    events:
      - http:
          path: /signup
          method: post
          cors: true
          summary: '회원가입 API'
          swaggerTags: ['User']
          bodyType: SignupDto


  login:
    handler: src/user/login.handler
    events:
      - http:
          path: /login
          method: post
          cors: true
          summary: '로그인 API'
          swaggerTags: ['User']
          bodyType: LoginDto


  postSchool:
    handler: src/admin/postSchool.handler
    events:
      - http:
          path: /school
          method: post
          cors: true
          summary: '학교 등록 API'
          swaggerTags: ['Admin']
          bodyType: postSchoolDto